/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AutofillRouteImport } from './routes/autofill'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as SettingsRouteImport } from './routes/settings'

const AutofillRoute = AutofillRouteImport.update({
  id: '/autofill',
  path: '/autofill',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/autofill': typeof AutofillRoute
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/autofill': typeof AutofillRoute
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/autofill': typeof AutofillRoute
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autofill' | '/memories' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autofill' | '/memories' | '/settings'
  id: '__root__' | '/' | '/autofill' | '/memories' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AutofillRoute: typeof AutofillRoute
  IndexRoute: typeof IndexRoute
  MemoriesRoute: typeof MemoriesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/autofill': {
      id: '/autofill'
      path: '/autofill'
      fullPath: '/autofill'
      preLoaderRoute: typeof AutofillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AutofillRoute: AutofillRoute,
  IndexRoute: IndexRoute,
  MemoriesRoute: MemoriesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
