/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AutofillRouteImport } from "./routes/autofill";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MemoriesRouteImport } from "./routes/memories";
import { Route as SettingsRouteImport } from "./routes/settings";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const MemoriesRoute = MemoriesRouteImport.update({
  id: "/memories",
  path: "/memories",
  getParentRoute: () => rootRouteImport,
} as any);
const AutofillRoute = AutofillRouteImport.update({
  id: "/autofill",
  path: "/autofill",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/autofill": typeof AutofillRoute;
  "/memories": typeof MemoriesRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/autofill": typeof AutofillRoute;
  "/memories": typeof MemoriesRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/autofill": typeof AutofillRoute;
  "/memories": typeof MemoriesRoute;
  "/settings": typeof SettingsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/autofill" | "/memories" | "/settings";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/autofill" | "/memories" | "/settings";
  id: "__root__" | "/" | "/autofill" | "/memories" | "/settings";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AutofillRoute: typeof AutofillRoute;
  MemoriesRoute: typeof MemoriesRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/memories": {
      id: "/memories";
      path: "/memories";
      fullPath: "/memories";
      preLoaderRoute: typeof MemoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/autofill": {
      id: "/autofill";
      path: "/autofill";
      fullPath: "/autofill";
      preLoaderRoute: typeof AutofillRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutofillRoute: AutofillRoute,
  MemoriesRoute: MemoriesRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
